### PR TITLE
fix tsan failures

### LINKED ISSUE #1486: ThreadSanitizer: data race in free (`fib::test::tests::test_concurrency_fibtable`)
- https://github.com/githedgehog/dataplane/actions/runs/24688622182/job/72205428105
- [logs_65428105576.zip](https://github.com/user-attachments/files/26937245/logs_65428105576.zip)

```
[60](https://github.com/githedgehog/dataplane/actions/runs/24688622182/job/72205428105?pr=1414#step:4:4262)
        FAIL [   5.035s] (715/717) dataplane-routing fib::test::tests::test_concurrency_fibtable
  stdout ───

    running 1 test
    Worker-1 started
    Worker-2 started
    Worker-3 started
    Worker-4 started
    Worker-5 started
    Worker-6 started
    Worker 3 is 10 % done
    Worker 2 is 10 % done
    Worker 5 is 10 % done
    Worker 6 is 10 % done
    Worker 1 is 10 % done
    Worker 3 is 20 % done
    Worker 2 is 20 % done
    Worker 5 is 20 % done
    Worker 4 is 10 % done
    Worker 1 is 20 % done
    Worker 2 is 30 % done
    Worker 6 is 20 % done
    Worker 3 is 30 % done
    Worker 4 is 20 % done
    Worker 5 is 30 % done
    Worker 1 is 30 % done
    Worker 3 is 40 % done
    Worker 2 is 40 % done
    Worker 4 is 30 % done
    Worker 6 is 30 % done
    Worker 5 is 40 % done
    Worker 1 is 40 % done
    Worker 3 is 50 % done
    Worker 2 is 50 % done
    Worker 4 is 40 % done
    Worker 6 is 40 % done
    Worker 5 is 50 % done
    Worker 1 is 50 % done
    Worker 3 is 60 % done
    Worker 2 is 60 % done
    Worker 4 is 50 % done
    Worker 6 is 50 % done
    Worker 5 is 60 % done
    Worker 1 is 60 % done
    Worker 3 is 70 % done
    Worker 2 is 70 % done
    Worker 4 is 60 % done
    Worker 6 is 60 % done
    Worker 5 is 70 % done
    Worker 1 is 70 % done
    Worker 3 is 80 % done
    Worker 4 is 70 % done
    Worker 2 is 80 % done
    Worker 6 is 70 % done
    Worker 5 is 80 % done
    Worker 1 is 80 % done
    Worker 3 is 90 % done
    Worker 4 is 80 % done
    Worker 2 is 90 % done
    Worker 6 is 80 % done
    Worker 5 is 90 % done
    Worker 1 is 90 % done
    Worker 3 is 100 % done
    === Worker 3 finished ====
    Stats:
        100000 packets hit 192.168.1.0/24
        481075 packets hit other prefix (0.0.0.0/0)
       2157547 packets found no fib
             1 packets found fib but could not enter
    Worker 2 is 100 % done
    === Worker 2 finished ====
    Stats:
        100000 packets hit 192.168.1.0/24
        475774 packets hit other prefix (0.0.0.0/0)
       2147693 packets found no fib
             1 packets found fib but could not enter
    Worker 6 is 90 % done
    Worker 4 is 90 % done
    Worker 5 is 100 % done
    === Worker 5 finished ====
    Stats:
        100000 packets hit 192.168.1.0/24
        488780 packets hit other prefix (0.0.0.0/0)
       2150472 packets found no fib
             1 packets found fib but could not enter
    Worker 1 is 100 % done
    === Worker 1 finished ====
    Stats:
        100000 packets hit 192.168.1.0/24
        493162 packets hit other prefix (0.0.0.0/0)
       2169696 packets found no fib
             3 packets found fib but could not enter
    Worker 4 is 100 % done
    === Worker 4 finished ====
    Stats:
        100000 packets hit 192.168.1.0/24
        512167 packets hit other prefix (0.0.0.0/0)
       2290108 packets found no fib
             6 packets found fib but could not enter
    Worker 6 is 100 % done
    === Worker 6 finished ====
    Stats:
        100000 packets hit 192.168.1.0/24
        502678 packets hit other prefix (0.0.0.0/0)
       2322303 packets found no fib
             6 packets found fib but could not enter
    All workers finished!
    Test duration: 4.952333856s
    test fib::test::tests::test_concurrency_fibtable ... ok

    test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 54 filtered out; finished in 4.98s

  stderr ───
    ==================
    WARNING: ThreadSanitizer: data race (pid=22476)
      Write of size 8 at 0x7238000070d0 by thread T1:
        #0 free <null> (dataplane_routing-d1e301da78a0a7d9+0x341e11) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #1 <std::alloc::System as core::alloc::global::GlobalAlloc>::dealloc /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/sys/alloc/unix.rs:48:18 (dataplane_routing-d1e301da78a0a7d9+0x3a5b61) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #2 __rustc::__rdl_dealloc /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/alloc.rs:463:25 (dataplane_routing-d1e301da78a0a7d9+0x3a5b61)
        #3 alloc::alloc::dealloc /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/alloc/src/alloc.rs:115:14 (dataplane_routing-d1e301da78a0a7d9+0x3a5b61)
        #4 <alloc::alloc::Global>::deallocate_impl_runtime /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/alloc/src/alloc.rs:209:22 (dataplane_routing-d1e301da78a0a7d9+0x3a5b61)
        #5 <alloc::alloc::Global>::deallocate_impl /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/alloc/src/alloc.rs:324:9 (dataplane_routing-d1e301da78a0a7d9+0x3a5b61)
        #6 <alloc::alloc::Global as core::alloc::Allocator>::deallocate /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/alloc/src/alloc.rs:442:23 (dataplane_routing-d1e301da78a0a7d9+0x3a5b61)
        #7 <alloc::boxed::Box<dataplane_routing::fib::fibtype::Fib> as core::ops::drop::Drop>::drop /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1921:24 (dataplane_routing-d1e301da78a0a7d9+0x3a5b61)
        #8 core::ptr::drop_in_place::<alloc::boxed::Box<dataplane_routing::fib::fibtype::Fib>> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:805:1 (dataplane_routing-d1e301da78a0a7d9+0x3a5b61)
        #9 <dataplane_routing::fib::fibtype::Fib as left_right::Absorb<dataplane_routing::fib::fibtype::FibChange>>::drop_second /nix/store/9ik3nfiv4azh087qd16bfxaxq9kr2n3m-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/left-right-0.11.7/src/lib.rs:252:38 (dataplane_routing-d1e301da78a0a7d9+0x45343f) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #10 <left_right::write::Taken<dataplane_routing::fib::fibtype::Fib, dataplane_routing::fib::fibtype::FibChange> as core::ops::drop::Drop>::drop /nix/store/9ik3nfiv4azh087qd16bfxaxq9kr2n3m-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/left-right-0.11.7/src/write.rs:135:13 (dataplane_routing-d1e301da78a0a7d9+0x45343f)
        #11 core::ptr::drop_in_place::<left_right::write::Taken<dataplane_routing::fib::fibtype::Fib, dataplane_routing::fib::fibtype::FibChange>> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:805:1 (dataplane_routing-d1e301da78a0a7d9+0x45343f)
        #12 <dataplane_routing::fib::fibtype::FibWriter>::destroy /nix/store/8qkm0gzpmbl03h8cy2xixxaq7yvyfs7d-source/routing/src/fib/fibtype.rs:392:5 (dataplane_routing-d1e301da78a0a7d9+0x45343f)
        #13 <dataplane_routing::fib::fibtype::Fib as left_right::Absorb<dataplane_routing::fib::fibtype::FibChange>>::drop_second /nix/store/9ik3nfiv4azh087qd16bfxaxq9kr2n3m-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/left-right-0.11.7/src/lib.rs:252:38 (dataplane_routing-d1e301da78a0a7d9+0x45343f) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #14 <left_right::write::Taken<dataplane_routing::fib::fibtype::Fib, dataplane_routing::fib::fibtype::FibChange> as core::ops::drop::Drop>::drop /nix/store/9ik3nfiv4azh087qd16bfxaxq9kr2n3m-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/left-right-0.11.7/src/write.rs:135:13 (dataplane_routing-d1e301da78a0a7d9+0x45343f)
        #15 core::ptr::drop_in_place::<left_right::write::Taken<dataplane_routing::fib::fibtype::Fib, dataplane_routing::fib::fibtype::FibChange>> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:805:1 (dataplane_routing-d1e301da78a0a7d9+0x45343f)
        #16 <dataplane_routing::fib::fibtype::FibWriter>::destroy /nix/store/8qkm0gzpmbl03h8cy2xixxaq7yvyfs7d-source/routing/src/fib/fibtype.rs:392:5 (dataplane_routing-d1e301da78a0a7d9+0x45343f)
        #17 dataplane_routing::fib::test::tests::test_concurrency_fibtable /nix/store/8qkm0gzpmbl03h8cy2xixxaq7yvyfs7d-source/routing/src/fib/test.rs:361:25 (dataplane_routing-d1e301da78a0a7d9+0x532b2f) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #18 dataplane_routing::fib::test::tests::test_concurrency_fibtable::{closure#0} /nix/store/8qkm0gzpmbl03h8cy2xixxaq7yvyfs7d-source/routing/src/fib/test.rs:250:35 (dataplane_routing-d1e301da78a0a7d9+0x532b2f)
        #19 <dataplane_routing::fib::test::tests::test_concurrency_fibtable::{closure#0} as core::ops::function::FnOnce<()>>::call_once /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5 (dataplane_routing-d1e301da78a0a7d9+0x532b2f)
        #20 <fn() -> core::result::Result<(), alloc::string::String> as core::ops::function::FnOnce<()>>::call_once /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5 (dataplane_routing-d1e301da78a0a7d9+0x552cd9) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #21 test::__rust_begin_short_backtrace::<core::result::Result<(), alloc::string::String>, fn() -> core::result::Result<(), alloc::string::String>> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/test/src/lib.rs:663:18 (dataplane_routing-d1e301da78a0a7d9+0x552cd9)
        #22 <test::types::RunnableTest>::run /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/test/src/types.rs:145:40 (dataplane_routing-d1e301da78a0a7d9+0x56af70) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #23 test::run_test_in_process::{closure#0} /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/test/src/lib.rs:686:74 (dataplane_routing-d1e301da78a0a7d9+0x56af70)
        #24 <core::panic::unwind_safe::AssertUnwindSafe<test::run_test_in_process::{closure#0}> as core::ops::function::FnOnce<()>>::call_once /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274:9 (dataplane_routing-d1e301da78a0a7d9+0x56af70)
        #25 std::panicking::catch_unwind::do_call::<core::panic::unwind_safe::AssertUnwindSafe<test::run_test_in_process::{closure#0}>, core::result::Result<(), alloc::string::String>> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panicking.rs:581:40 (dataplane_routing-d1e301da78a0a7d9+0x56af70)
        #26 __rust_try test.1c5a198dc2bfd776-cgu.0 (dataplane_routing-d1e301da78a0a7d9+0x5b7a61) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #27 __rust_try test.1c5a198dc2bfd776-cgu.0 (dataplane_routing-d1e301da78a0a7d9+0x5b7a61) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #28 std::panicking::catch_unwind::<core::result::Result<(), alloc::string::String>, core::panic::unwind_safe::AssertUnwindSafe<test::run_test_in_process::{closure#0}>> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panicking.rs:544:19 (dataplane_routing-d1e301da78a0a7d9+0x570a82) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #29 std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<test::run_test_in_process::{closure#0}>, core::result::Result<(), alloc::string::String>> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panic.rs:359:14 (dataplane_routing-d1e301da78a0a7d9+0x570a82)
        #30 test::run_test_in_process /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/test/src/lib.rs:686:27 (dataplane_routing-d1e301da78a0a7d9+0x570a82)
        #31 test::run_test::{closure#0} /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/test/src/lib.rs:607:43 (dataplane_routing-d1e301da78a0a7d9+0x570a82)
        #32 test::run_test::{closure#1} /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/test/src/lib.rs:637:41 (dataplane_routing-d1e301da78a0a7d9+0x566849) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #33 std::sys::backtrace::__rust_begin_short_backtrace::<test::run_test::{closure#1}, ()> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:166:18 (dataplane_routing-d1e301da78a0a7d9+0x566849)
        #34 std::thread::lifecycle::spawn_unchecked::<test::run_test::{closure#1}, ()>::{closure#1}::{closure#0} /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:91:13 (dataplane_routing-d1e301da78a0a7d9+0x56ae66) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #35 <core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked<test::run_test::{closure#1}, ()>::{closure#1}::{closure#0}> as core::ops::function::FnOnce<()>>::call_once /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274:9 (dataplane_routing-d1e301da78a0a7d9+0x56ae66)
        #36 std::panicking::catch_unwind::do_call::<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked<test::run_test::{closure#1}, ()>::{closure#1}::{closure#0}>, ()> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panicking.rs:581:40 (dataplane_routing-d1e301da78a0a7d9+0x56ae66)
        #37 __rust_try test.1c5a198dc2bfd776-cgu.0 (dataplane_routing-d1e301da78a0a7d9+0x5b7a61) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #38 std::panicking::catch_unwind::<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked<test::run_test::{closure#1}, ()>::{closure#1}::{closure#0}>> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panicking.rs:544:19 (dataplane_routing-d1e301da78a0a7d9+0x5750e3) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #39 std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked<test::run_test::{closure#1}, ()>::{closure#1}::{closure#0}>, ()> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panic.rs:359:14 (dataplane_routing-d1e301da78a0a7d9+0x5750e3)
        #40 std::thread::lifecycle::spawn_unchecked::<test::run_test::{closure#1}, ()>::{closure#1} /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:89:26 (dataplane_routing-d1e301da78a0a7d9+0x5750e3)
        #41 <std::thread::lifecycle::spawn_unchecked<test::run_test::{closure#1}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0} /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5 (dataplane_routing-d1e301da78a0a7d9+0x5750e3)
        #42 <alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output = ()> + core::marker::Send> as core::ops::function::FnOnce<()>>::call_once /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2240:9 (dataplane_routing-d1e301da78a0a7d9+0xa2bb0b) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #43 <std::sys::thread::unix::Thread>::new::thread_start /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/sys/thread/unix.rs:118:17 (dataplane_routing-d1e301da78a0a7d9+0xa2bb0b)

      Previous read of size 1 at 0x7238000070d0 by thread T7:
        #0 <dataplane_routing::fib::fibtype::FibReader>::enter::{closure#0} /nix/store/8qkm0gzpmbl03h8cy2xixxaq7yvyfs7d-source/routing/src/fib/fibtype.rs:414:27 (dataplane_routing-d1e301da78a0a7d9+0x3d3ab0) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #1 <core::option::Option<left_right::read::guard::ReadGuard<dataplane_routing::fib::fibtype::Fib>>>::map::<core::option::Option<left_right::read::guard::ReadGuard<dataplane_routing::fib::fibtype::Fib>>, <dataplane_routing::fib::fibtype::FibReader>::enter::{closure#0}> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/core/src/option.rs:1165:29 (dataplane_routing-d1e301da78a0a7d9+0x3d3ab0)
        #2 <dataplane_routing::fib::fibtype::FibReader>::enter /nix/store/8qkm0gzpmbl03h8cy2xixxaq7yvyfs7d-source/routing/src/fib/fibtype.rs:414:14 (dataplane_routing-d1e301da78a0a7d9+0x3d3ab0)
        #3 dataplane_routing::fib::test::tests::test_concurrency_fibtable::{closure#0} /nix/store/8qkm0gzpmbl03h8cy2xixxaq7yvyfs7d-source/routing/src/fib/test.rs:288:52 (dataplane_routing-d1e301da78a0a7d9+0x3d3ab0)
        #4 std::sys::backtrace::__rust_begin_short_backtrace::<dataplane_routing::fib::test::tests::test_concurrency_fibtable::{closure#0}, ()> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:166:18 (dataplane_routing-d1e301da78a0a7d9+0x3d3ab0)
        #5 std::thread::lifecycle::spawn_unchecked::<dataplane_routing::fib::test::tests::test_concurrency_fibtable::{closure#0}, ()>::{closure#1}::{closure#0} /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:91:13 (dataplane_routing-d1e301da78a0a7d9+0x3dfca3) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #6 <core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked<dataplane_routing::fib::test::tests::test_concurrency_fibtable::{closure#0}, ()>::{closure#1}::{closure#0}> as core::ops::function::FnOnce<()>>::call_once /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274:9 (dataplane_routing-d1e301da78a0a7d9+0x3dfca3)
        #7 std::panicking::catch_unwind::do_call::<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked<dataplane_routing::fib::test::tests::test_concurrency_fibtable::{closure#0}, ()>::{closure#1}::{closure#0}>, ()> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panicking.rs:581:40 (dataplane_routing-d1e301da78a0a7d9+0x3dfca3)
        #8 __rust_try dataplane_routing.75c8a3f6a0124f60-cgu.0 (dataplane_routing-d1e301da78a0a7d9+0x551b01) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #9 std::panicking::catch_unwind::<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked<dataplane_routing::fib::test::tests::test_concurrency_fibtable::{closure#0}, ()>::{closure#1}::{closure#0}>> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panicking.rs:544:19 (dataplane_routing-d1e301da78a0a7d9+0x42340a) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #10 std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked<dataplane_routing::fib::test::tests::test_concurrency_fibtable::{closure#0}, ()>::{closure#1}::{closure#0}>, ()> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panic.rs:359:14 (dataplane_routing-d1e301da78a0a7d9+0x42340a)
        #11 std::thread::lifecycle::spawn_unchecked::<dataplane_routing::fib::test::tests::test_concurrency_fibtable::{closure#0}, ()>::{closure#1} /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:89:26 (dataplane_routing-d1e301da78a0a7d9+0x42340a)
        #12 <std::thread::lifecycle::spawn_unchecked<dataplane_routing::fib::test::tests::test_concurrency_fibtable::{closure#0}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0} /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5 (dataplane_routing-d1e301da78a0a7d9+0x42340a)
        #13 <alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output = ()> + core::marker::Send> as core::ops::function::FnOnce<()>>::call_once /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2240:9 (dataplane_routing-d1e301da78a0a7d9+0xa2bb0b) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #14 <std::sys::thread::unix::Thread>::new::thread_start /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/sys/thread/unix.rs:118:17 (dataplane_routing-d1e301da78a0a7d9+0xa2bb0b)

      Thread T1 'fib::test::test' (tid=22486, running) created by main thread at:
        #0 pthread_create <null> (dataplane_routing-d1e301da78a0a7d9+0x2f22dc) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #1 <std::sys::thread::unix::Thread>::new /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/sys/thread/unix.rs:98:19 (dataplane_routing-d1e301da78a0a7d9+0x9fe1d4) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #2 std::thread::lifecycle::spawn_unchecked::<test::run_test::{closure#1}, ()> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:137:26 (dataplane_routing-d1e301da78a0a7d9+0x576fd3) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #3 <std::thread::builder::Builder>::spawn_unchecked::<test::run_test::{closure#1}, ()> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/thread/builder.rs:261:32 (dataplane_routing-d1e301da78a0a7d9+0x576fd3)
        #4 <std::thread::builder::Builder>::spawn::<test::run_test::{closure#1}, ()> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/thread/builder.rs:191:23 (dataplane_routing-d1e301da78a0a7d9+0x576fd3)
        #5 test::run_test /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/test/src/lib.rs:637:27 (dataplane_routing-d1e301da78a0a7d9+0x576fd3)
        #6 test::run_tests::<test::console::run_tests_console::{closure#2}> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/test/src/lib.rs:447:21 (dataplane_routing-d1e301da78a0a7d9+0x595acc) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #7 test::console::run_tests_console /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/test/src/console.rs:327:5 (dataplane_routing-d1e301da78a0a7d9+0x595acc)
        #8 test::test_main_with_exit_callback::<test::test_main::{closure#0}> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/test/src/lib.rs:160:19 (dataplane_routing-d1e301da78a0a7d9+0x578845) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #9 test::test_main /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/test/src/lib.rs:101:5 (dataplane_routing-d1e301da78a0a7d9+0x578845)
        #10 test::test_main_static /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/test/src/lib.rs:183:5 (dataplane_routing-d1e301da78a0a7d9+0x575efb) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #11 dataplane_routing::main /nix/store/8qkm0gzpmbl03h8cy2xixxaq7yvyfs7d-source/routing/src/lib.rs (dataplane_routing-d1e301da78a0a7d9+0x42368f) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #12 <fn() as core::ops::function::FnOnce<()>>::call_once /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5 (dataplane_routing-d1e301da78a0a7d9+0x3d09ff) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #13 std::sys::backtrace::__rust_begin_short_backtrace::<fn(), ()> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:166:18 (dataplane_routing-d1e301da78a0a7d9+0x3d09ff)
        #14 std::rt::lang_start::<()>::{closure#0} /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/rt.rs:206:18 (dataplane_routing-d1e301da78a0a7d9+0x3f14c1) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #15 <&dyn core::ops::function::Fn<(), Output = i32> + core::panic::unwind_safe::RefUnwindSafe + core::marker::Sync as core::ops::function::FnOnce<()>>::call_once /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/core/src/ops/function.rs:287:21 (dataplane_routing-d1e301da78a0a7d9+0x9eed69) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #16 std::panicking::catch_unwind::do_call::<&dyn core::ops::function::Fn<(), Output = i32> + core::panic::unwind_safe::RefUnwindSafe + core::marker::Sync, i32> (.llvm.10046069462335036339) /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panicking.rs:581:40 (dataplane_routing-d1e301da78a0a7d9+0x9eed69)
        #17 __rust_try.llvm.10046069462335036339 std.ff82bb5f7db24ecb-cgu.0 (dataplane_routing-d1e301da78a0a7d9+0xa39095) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #18 std::panicking::catch_unwind::<i32, &dyn core::ops::function::Fn<(), Output = i32> + core::panic::unwind_safe::RefUnwindSafe + core::marker::Sync> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panicking.rs:544:19 (dataplane_routing-d1e301da78a0a7d9+0x9eeaa4) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #19 std::panic::catch_unwind::<&dyn core::ops::function::Fn<(), Output = i32> + core::panic::unwind_safe::RefUnwindSafe + core::marker::Sync, i32> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panic.rs:359:14 (dataplane_routing-d1e301da78a0a7d9+0x9eeaa4)
        #20 std::rt::lang_start_internal::{closure#0} /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/rt.rs:175:24 (dataplane_routing-d1e301da78a0a7d9+0x9eeaa4)
        #21 std::panicking::catch_unwind::do_call::<std::rt::lang_start_internal::{closure#0}, isize> (.llvm.10046069462335036339) /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panicking.rs:581:40 (dataplane_routing-d1e301da78a0a7d9+0x9eeaa4)
        #22 __rust_try.llvm.10046069462335036339 std.ff82bb5f7db24ecb-cgu.0 (dataplane_routing-d1e301da78a0a7d9+0xa39095) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #23 std::panicking::catch_unwind::<isize, std::rt::lang_start_internal::{closure#0}> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panicking.rs:544:19 (dataplane_routing-d1e301da78a0a7d9+0xa1e33a) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #24 std::panic::catch_unwind::<std::rt::lang_start_internal::{closure#0}, isize> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panic.rs:359:14 (dataplane_routing-d1e301da78a0a7d9+0xa1e33a)
        #25 std::rt::lang_start_internal /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/rt.rs:171:5 (dataplane_routing-d1e301da78a0a7d9+0xa1e33a)
        #26 main <null> (dataplane_routing-d1e301da78a0a7d9+0x551b91) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)

      Thread T7 'WORKER-6' (tid=22496, running) created by thread T1 at:
        #0 pthread_create <null> (dataplane_routing-d1e301da78a0a7d9+0x2f22dc) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #1 <std::sys::thread::unix::Thread>::new /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/sys/thread/unix.rs:98:19 (dataplane_routing-d1e301da78a0a7d9+0x9fe1d4) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #2 std::thread::lifecycle::spawn_unchecked::<dataplane_routing::fib::test::tests::test_concurrency_fibtable::{closure#0}, ()> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:137:26 (dataplane_routing-d1e301da78a0a7d9+0x532296) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #3 <std::thread::builder::Builder>::spawn_unchecked::<dataplane_routing::fib::test::tests::test_concurrency_fibtable::{closure#0}, ()> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/thread/builder.rs:261:32 (dataplane_routing-d1e301da78a0a7d9+0x532296)
        #4 <std::thread::builder::Builder>::spawn::<dataplane_routing::fib::test::tests::test_concurrency_fibtable::{closure#0}, ()> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/thread/builder.rs:191:23 (dataplane_routing-d1e301da78a0a7d9+0x532296)
        #5 dataplane_routing::fib::test::tests::test_concurrency_fibtable /nix/store/8qkm0gzpmbl03h8cy2xixxaq7yvyfs7d-source/routing/src/fib/test.rs:277:18 (dataplane_routing-d1e301da78a0a7d9+0x532296)
        #6 dataplane_routing::fib::test::tests::test_concurrency_fibtable::{closure#0} /nix/store/8qkm0gzpmbl03h8cy2xixxaq7yvyfs7d-source/routing/src/fib/test.rs:250:35 (dataplane_routing-d1e301da78a0a7d9+0x532296)
        #7 <dataplane_routing::fib::test::tests::test_concurrency_fibtable::{closure#0} as core::ops::function::FnOnce<()>>::call_once /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5 (dataplane_routing-d1e301da78a0a7d9+0x532296)
        #8 <fn() -> core::result::Result<(), alloc::string::String> as core::ops::function::FnOnce<()>>::call_once /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5 (dataplane_routing-d1e301da78a0a7d9+0x552cd9) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #9 test::__rust_begin_short_backtrace::<core::result::Result<(), alloc::string::String>, fn() -> core::result::Result<(), alloc::string::String>> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/test/src/lib.rs:663:18 (dataplane_routing-d1e301da78a0a7d9+0x552cd9)
        #10 <test::types::RunnableTest>::run /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/test/src/types.rs:145:40 (dataplane_routing-d1e301da78a0a7d9+0x56af70) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #11 test::run_test_in_process::{closure#0} /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/test/src/lib.rs:686:74 (dataplane_routing-d1e301da78a0a7d9+0x56af70)
        #12 <core::panic::unwind_safe::AssertUnwindSafe<test::run_test_in_process::{closure#0}> as core::ops::function::FnOnce<()>>::call_once /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274:9 (dataplane_routing-d1e301da78a0a7d9+0x56af70)
        #13 std::panicking::catch_unwind::do_call::<core::panic::unwind_safe::AssertUnwindSafe<test::run_test_in_process::{closure#0}>, core::result::Result<(), alloc::string::String>> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panicking.rs:581:40 (dataplane_routing-d1e301da78a0a7d9+0x56af70)
        #14 __rust_try test.1c5a198dc2bfd776-cgu.0 (dataplane_routing-d1e301da78a0a7d9+0x5b7a61) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #15 __rust_try test.1c5a198dc2bfd776-cgu.0 (dataplane_routing-d1e301da78a0a7d9+0x5b7a61) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #16 std::panicking::catch_unwind::<core::result::Result<(), alloc::string::String>, core::panic::unwind_safe::AssertUnwindSafe<test::run_test_in_process::{closure#0}>> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panicking.rs:544:19 (dataplane_routing-d1e301da78a0a7d9+0x570a82) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #17 std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<test::run_test_in_process::{closure#0}>, core::result::Result<(), alloc::string::String>> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panic.rs:359:14 (dataplane_routing-d1e301da78a0a7d9+0x570a82)
        #18 test::run_test_in_process /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/test/src/lib.rs:686:27 (dataplane_routing-d1e301da78a0a7d9+0x570a82)
        #19 test::run_test::{closure#0} /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/test/src/lib.rs:607:43 (dataplane_routing-d1e301da78a0a7d9+0x570a82)
        #20 test::run_test::{closure#1} /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/test/src/lib.rs:637:41 (dataplane_routing-d1e301da78a0a7d9+0x566849) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #21 std::sys::backtrace::__rust_begin_short_backtrace::<test::run_test::{closure#1}, ()> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:166:18 (dataplane_routing-d1e301da78a0a7d9+0x566849)
        #22 std::thread::lifecycle::spawn_unchecked::<test::run_test::{closure#1}, ()>::{closure#1}::{closure#0} /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:91:13 (dataplane_routing-d1e301da78a0a7d9+0x56ae66) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #23 <core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked<test::run_test::{closure#1}, ()>::{closure#1}::{closure#0}> as core::ops::function::FnOnce<()>>::call_once /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:274:9 (dataplane_routing-d1e301da78a0a7d9+0x56ae66)
        #24 std::panicking::catch_unwind::do_call::<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked<test::run_test::{closure#1}, ()>::{closure#1}::{closure#0}>, ()> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panicking.rs:581:40 (dataplane_routing-d1e301da78a0a7d9+0x56ae66)
        #25 __rust_try test.1c5a198dc2bfd776-cgu.0 (dataplane_routing-d1e301da78a0a7d9+0x5b7a61) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #26 std::panicking::catch_unwind::<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked<test::run_test::{closure#1}, ()>::{closure#1}::{closure#0}>> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panicking.rs:544:19 (dataplane_routing-d1e301da78a0a7d9+0x5750e3) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #27 std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<std::thread::lifecycle::spawn_unchecked<test::run_test::{closure#1}, ()>::{closure#1}::{closure#0}>, ()> /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/panic.rs:359:14 (dataplane_routing-d1e301da78a0a7d9+0x5750e3)
        #28 std::thread::lifecycle::spawn_unchecked::<test::run_test::{closure#1}, ()>::{closure#1} /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/thread/lifecycle.rs:89:26 (dataplane_routing-d1e301da78a0a7d9+0x5750e3)
        #29 <std::thread::lifecycle::spawn_unchecked<test::run_test::{closure#1}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0} /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5 (dataplane_routing-d1e301da78a0a7d9+0x5750e3)
        #30 <alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output = ()> + core::marker::Send> as core::ops::function::FnOnce<()>>::call_once /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2240:9 (dataplane_routing-d1e301da78a0a7d9+0xa2bb0b) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7)
        #31 <std::sys::thread::unix::Thread>::new::thread_start /nix/store/nq3zc3srfcvk0xgcxyn6q36bsi56wpv1-rust-default-1.95.0/lib/rustlib/src/rust/library/std/src/sys/thread/unix.rs:118:17 (dataplane_routing-d1e301da78a0a7d9+0xa2bb0b)

    SUMMARY: ThreadSanitizer: data race (/home/runner/_work/_temp/nix-shell-2461-4031438536/nextest-archive-3VT7jq/target/x86_64-unknown-linux-gnu/fuzz/deps/dataplane_routing-d1e301da78a0a7d9+0x341e11) (BuildId: 6145a01ef035efff351b0c7d308d928c60d210f7) in free
    ==================
    ThreadSanitizer: reported 1 warnings

    (test failed with exit code 66)

        PASS [   5.295s] (716/717) dataplane-routing fib::test::tests::test_fib_removals
        PASS [   8.095s] (717/717) dataplane-routing atable::resolver::tests::test_adjacency_resolver
────────────
     Summary [  14.972s] 717 tests run: 716 passed, 1 failed, 15 skipped
        FAIL [   5.035s] (715/717) dataplane-routing fib::test::tests::test_concurrency_fibtable
```

### PR DESCRIPTION
**Pull request by Fredi-raspall**
Closes https://github.com/githedgehog/dataplane/issues/1486

This PR does not actually fix anything but:
  - does inoffensive clean-ups
  - adds a test that shows that the issue is in left-right
  - points our cargo.toml to a local fork of left-right with a fix.

### CODE REVIEW

File: routing/src/fib/fibtype.rs [hunk 1]
```diff
@@ -385,6 +384,8 @@ impl FibWriter {
         FibReader::new(self.0.clone())
     }
     pub fn destroy(mut self) {
+        self.0.append(FibChange::Invalidate);
+        self.0.publish();
```
Comment (qmonnet) [inline routing/src/fib/fibtype.rs]: Nit: This looks unrelated to the rest of commit `feat(routing): avoid unwrap_or_else + unreachable`, and you remove it in the next commit. Maybe don't add it at all?

File: routing/src/fib/test.rs [hunk 2]
```diff
@@ -429,6 +429,114 @@ mod tests {
...
+    // Minimal reproducer for the TSAN race reported on `test_concurrency_fibtable`.
+    //
+    // Uses `left_right` directly with a trivial struct that has no interior
+    // allocations and no relationship to `Fib`, `FibTable`, or the
+    // `ReadHandleCache` (no thread-local storage). If this test races under
+    // ThreadSanitizer, the bug lives in `left_right::WriteHandle::drop` (in
+    // `take_inner`: NULL-swap followed by `wait()` on stale `last_epochs`),
+    // *not* in our code.
+    #[test]
+    fn test_leftright_destroy_race_simple() {
```
Comment (qmonnet) [inline routing/src/fib/test.rs:441]: It's great to have the reproducer, but isn't this going to trigger the sanitizer job in our CI?

File: Cargo.toml [hunk 3]
```diff
@@ -125,7 +125,8 @@ k8s-openapi = { version = "0.27.1", default-features = false, features = [] }
 kanal = { version = "0.1.1", default-features = false, features = [] }
 kube = { version = "3.1.0", default-features = false, features = [] }
 kube-core = { version = "3.1.0", default-features = false, features = [] }
-left-right = { version = "0.11.7", default-features = false, features = [] }
+#left-right = { version = "0.11.7", default-features = false, features = [] }
+left-right = { git = "https://github.com/githedgehog/left-right.git", branch = "fredi/fix-writehandle-drop", default-features = false, features = [] }
```
Comment (qmonnet) [inline Cargo.toml:129]: Arf 😕 Can we please open a PR against the upstream repo to see if they can fix it, so we can discard the custom fork as soon as possible?

File: routing/src/fib/test.rs [hunk 4]
```diff
@@ -429,6 +429,114 @@ mod tests {
...
+                                        enters += 1;
+                                    }
+                                }
+                                None => misses += 1,
+                            }
+                        }
+                        if stop.load(Ordering::Relaxed) {
+                            break;
+                        }
+                    }
```
[the remark this answers is not in the document]
Comment (Fredi-raspall) [reply routing/src/fib/test.rs:503]: That's intended.

**Comment by qmonnet** [comment]
RUSTSEC issue in CI will require a rebase on top of #1489, once it's merged.

File: Cargo.toml (hunk 3 above)
[the remark this answers is not in the document]
Comment (Fredi-raspall) [reply Cargo.toml:129]: We do this for other dependencies. May address later once we clarify the best practice that suits us.

File: routing/src/fib/test.rs (hunk 2 above)
Comment (Fredi-raspall) [reply routing/src/fib/test.rs:441]: No because we'll use a distinct left-right.

File: Cargo.toml (hunk 3 above)
Comment (Fredi-raspall) [reply Cargo.toml:129]: Yes, once we know it's the right fix.

File: routing/src/fib/test.rs [hunk 5]
```diff
@@ -429,6 +429,114 @@ mod tests {
...
+        }
+
+        const NUM_WORKERS: u16 = 6;
+        const ITERATIONS: usize = 5_000;
+
+        // Slot carrying the current generation's ReadHandleFactory (or None
+        // between generations). Workers fetch a fresh `ReadHandle` from it and
+        // then `.enter()` — mirroring the `FibReader::enter` access pattern but
+        // without any thread-local cache in the way.
+        let slot: Arc<RwLock<Option<ReadHandleFactory<Tiny>>>> = Arc::new(RwLock::new(None));
```
[the remark this answers is not in the document]
Comment (Fredi-raspall) [reply routing/src/fib/test.rs]: changed

File: routing/src/fib/test.rs [hunk 6]
```diff
@@ -429,6 +429,114 @@ mod tests {
...
+            valid: bool,
+            payload: u64,
+        }
+        enum TinyOp {
+            Invalidate,
+        }
+        impl Absorb<TinyOp> for Tiny {
+            fn absorb_first(&mut self, op: &mut TinyOp, _: &Self) {
+                match op {
+                    TinyOp::Invalidate => self.valid = false,
```
[the remark this answers is not in the document]
Comment (Fredi-raspall) [reply routing/src/fib/test.rs:456]: I think this is fine as it is and does not cause the linter to complain.

File: routing/src/fib/test.rs [hunk 7]
```diff
@@ -429,6 +429,114 @@ mod tests {
...
+                    let mut misses = 0u64;
+                    loop {
+                        let rh: Option<ReadHandle<Tiny>> =
+                            slot.read().unwrap().as_ref().map(ReadHandleFactory::handle);
+                        if let Some(rh) = rh {
+                            match rh.enter() {
+                                Some(g) => {
+                                    // Read the `valid` byte — this is the
+                                    // same size-1 read that TSAN caught at
+                                    // `fibtype.rs:415:16`.
```
[the remark this answers is not in the document]
Comment (Fredi-raspall) [reply routing/src/fib/test.rs]: fixed

File: routing/src/fib/fibtype.rs (hunk 1 above)
Comment (Fredi-raspall) [reply routing/src/fib/fibtype.rs]: Yes, that was a rebase artifact probably.

File: routing/src/fib/test.rs (hunk 2 above)
Comment (qmonnet) [reply routing/src/fib/test.rs:441]: :facepalm: of course, that was silly

File: routing/src/fib/fibtype.rs (hunk 1 above)
Comment (qmonnet) [reply routing/src/fib/fibtype.rs]: Can you please fix it?

Comment (qmonnet) [reply routing/src/fib/fibtype.rs]: Fixed (and rebased on `main`).

**Review by qmonnet — APPROVED** [review]
Looks good, thanks!

Please submit the left-right PR upstream as soon as you're more confident in the fix.
